// Generated by scripts/generate-website-config.mjs — public Supabase read config only
window.__TROTROOS_PUBLIC__ = Object.freeze({
  supabaseUrl: "https://kqozxewmiykdyjzupkip.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxb3p4ZXdtaXlrZHlqenVwa2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NjczNzUsImV4cCI6MjA5OTU0MzM3NX0.u-6Hv3FN2Qs0c-htqLulOd4ArNE5HcnpAUFWnvV6pPE",
});
